// <auto-generated />
using System;
using FollowUp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace FollowUp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FollowUpDbContext))]
    [Migration("20260122192155_AttendanceRaceConditionFix")]
    partial class AttendanceRaceConditionFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FollowUp.Core.Entities.Appeal", b =>
                {
                    b.Property<int>("AppealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppealId"));

                    b.Property<int>("AppealType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistanceMeters")
                        .HasColumnType("int");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EvidencePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("ExpectedLatitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double?>("ExpectedLongitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalRejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WorkerExplanation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double?>("WorkerLatitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double?>("WorkerLongitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.HasKey("AppealId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Appeal_Status");

                    b.HasIndex("SubmittedAt")
                        .HasDatabaseName("IX_Appeal_SubmittedAt");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_Appeal_Entity");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_Appeal_User_Status");

                    b.ToTable("Appeals");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("AttendanceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CheckInDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("CAST([CheckInEventTime] AS DATE)", true);

                    b.Property<DateTime>("CheckInEventTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("CheckInLatitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double>("CheckInLongitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<DateTime?>("CheckInSyncTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutEventTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CheckOutLatitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double?>("CheckOutLongitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<DateTime?>("CheckOutSyncTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EarlyLeaveMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsManual")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<int>("LateMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ManualReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<int>("OvertimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ValidationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan?>("WorkDuration")
                        .HasColumnType("time");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Attendance_Status");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("IX_Attendance_ZoneId");

                    b.HasIndex("UserId", "CheckInDate")
                        .IsUnique()
                        .HasDatabaseName("IX_Attendance_UniqueActiveCheckIn")
                        .HasFilter("[Status] = 1");

                    b.HasIndex("UserId", "CheckInEventTime")
                        .HasDatabaseName("IX_Attendance_User_CheckIn");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditLogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Department_IsActive");

                    b.HasIndex("MunicipalityId")
                        .HasDatabaseName("IX_Department_MunicipalityId");

                    b.HasIndex("MunicipalityId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Department_Municipality_Code_Unique");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.GisFile", b =>
                {
                    b.Property<int>("GisFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GisFileId"));

                    b.Property<int>("FeaturesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("GisFileId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("FileType", "IsActive")
                        .HasDatabaseName("IX_GisFile_Type_Active");

                    b.ToTable("GisFiles");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Issue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IssueId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Longitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SyncTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("IssueId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("ReportedAt");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("Severity");

                    b.HasIndex("Type");

                    b.HasIndex("ZoneId");

                    b.HasIndex("ReportedByUserId", "Status")
                        .HasDatabaseName("IX_Issue_Reporter_Status");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.LocationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Accuracy")
                        .HasColumnType("float");

                    b.Property<double?>("Heading")
                        .HasColumnType("float");

                    b.Property<bool>("IsSync")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double>("Longitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double?>("Speed")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp")
                        .HasDatabaseName("IX_LocationHistory_User_Timestamp");

                    b.ToTable("LocationHistories");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Municipality", b =>
                {
                    b.Property<int>("MunicipalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MunicipalityId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("DefaultEndTime")
                        .HasColumnType("time");

                    b.Property<int>("DefaultGraceMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15);

                    b.Property<TimeSpan>("DefaultStartTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LicenseExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("MaxAcceptableAccuracyMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(150.0);

                    b.Property<double>("MaxLatitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double>("MaxLongitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double>("MinLatitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double>("MinLongitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MunicipalityId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Municipality_Code_Unique");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Municipality_IsActive");

                    b.ToTable("Municipalities");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FcmMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsSent");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("Type");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("IX_Notification_User_IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("IssueId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("PhotoId");

                    b.HasIndex("IssueId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("IX_Photos_UploadedAt");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_Photos_EntityType_EntityId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CompletionDistanceMeters")
                        .HasColumnType("int");

                    b.Property<string>("CompletionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExtendedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExtendedDeadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedCompletionAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsAutoRejected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDistanceWarning")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTeamTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double?>("Latitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("Longitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<int>("MaxDistanceMeters")
                        .HasColumnType("int");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ProgressNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RejectedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("RejectionDistanceMeters")
                        .HasColumnType("int");

                    b.Property<double?>("RejectionLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("RejectionLongitude")
                        .HasColumnType("float");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresPhotoProof")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SyncTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int");

                    b.Property<int?>("TaskType")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("DueDate");

                    b.HasIndex("IsTeamTask")
                        .HasDatabaseName("IX_Task_IsTeamTask");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("Priority");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_Task_TeamId");

                    b.HasIndex("ZoneId");

                    b.HasIndex("AssignedToUserId", "Status")
                        .HasDatabaseName("IX_Task_AssignedUser_Status");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.TaskTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("ZoneId");

                    b.ToTable("TaskTemplates");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TeamLeaderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TeamId");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Team_DepartmentId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Team_IsActive");

                    b.HasIndex("TeamLeaderId")
                        .HasDatabaseName("IX_Team_TeamLeaderId");

                    b.HasIndex("DepartmentId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Team_Department_Code_Unique");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.TwoFactorCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("PendingJwtToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_TwoFactorCode_ExpiresAt");

                    b.HasIndex("UserId", "IsUsed", "ExpiresAt")
                        .HasDatabaseName("IX_TwoFactorCode_User_Active");

                    b.ToTable("TwoFactorCodes");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("ExpectedEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ExpectedStartTime")
                        .HasColumnType("time");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GraceMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsLowBattery")
                        .HasColumnType("bit");

                    b.Property<int?>("LastBatteryLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastBatteryReportTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastWarningAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastWarningReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockoutEndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RegisteredDeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WarningCount")
                        .HasColumnType("int");

                    b.Property<int?>("WorkerType")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("TeamId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.UserZone", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "ZoneId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_UserZone_IsActive");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserZone_UserId");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("IX_UserZone_ZoneId");

                    b.ToTable("UserZones");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Zone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"));

                    b.Property<double>("AreaSquareMeters")
                        .HasColumnType("float");

                    b.Property<Geometry>("Boundary")
                        .HasColumnType("geography");

                    b.Property<string>("BoundaryGeoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CenterLatitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double>("CenterLongitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<DateTime>("VersionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ZoneCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ZoneId");

                    b.HasIndex("District");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Zone_IsActive");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("ZoneCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Zone_ZoneCode_Unique");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Appeal", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.Municipality", "Municipality")
                        .WithMany("Appeals")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowUp.Core.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FollowUp.Core.Entities.User", "User")
                        .WithMany("Appeals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipality");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Attendance", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId");

                    b.HasOne("FollowUp.Core.Entities.Municipality", "Municipality")
                        .WithMany("Attendances")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowUp.Core.Entities.User", "User")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowUp.Core.Entities.Zone", "Zone")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Municipality");

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Department", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.Municipality", "Municipality")
                        .WithMany("Departments")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.GisFile", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Issue", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.Municipality", "Municipality")
                        .WithMany("Issues")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowUp.Core.Entities.User", "ReportedByUser")
                        .WithMany("ReportedIssues")
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowUp.Core.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FollowUp.Core.Entities.Zone", "Zone")
                        .WithMany("Issues")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Municipality");

                    b.Navigation("ReportedByUser");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.LocationHistory", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Notification", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.Municipality", "Municipality")
                        .WithMany("Notifications")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowUp.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Photo", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.Issue", "Issue")
                        .WithMany("Photos")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FollowUp.Core.Entities.Task", "Task")
                        .WithMany("Photos")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FollowUp.Core.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Issue");

                    b.Navigation("Task");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Task", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FollowUp.Core.Entities.User", "AssignedToUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowUp.Core.Entities.Municipality", "Municipality")
                        .WithMany("Tasks")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowUp.Core.Entities.Team", "Team")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FollowUp.Core.Entities.Zone", "Zone")
                        .WithMany("Tasks")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Municipality");

                    b.Navigation("Team");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.TaskTemplate", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FollowUp.Core.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.Navigation("Municipality");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Team", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.Department", "Department")
                        .WithMany("Teams")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowUp.Core.Entities.User", "TeamLeader")
                        .WithMany()
                        .HasForeignKey("TeamLeaderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("TeamLeader");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.TwoFactorCode", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.User", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FollowUp.Core.Entities.Municipality", "Municipality")
                        .WithMany("Users")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowUp.Core.Entities.User", "Supervisor")
                        .WithMany("SupervisedWorkers")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FollowUp.Core.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Municipality");

                    b.Navigation("Supervisor");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.UserZone", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowUp.Core.Entities.User", "User")
                        .WithMany("AssignedZones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FollowUp.Core.Entities.Zone", "Zone")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Zone", b =>
                {
                    b.HasOne("FollowUp.Core.Entities.Municipality", "Municipality")
                        .WithMany("Zones")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Department", b =>
                {
                    b.Navigation("Teams");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Issue", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Municipality", b =>
                {
                    b.Navigation("Appeals");

                    b.Navigation("Attendances");

                    b.Navigation("Departments");

                    b.Navigation("Issues");

                    b.Navigation("Notifications");

                    b.Navigation("Tasks");

                    b.Navigation("Users");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Task", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Team", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.User", b =>
                {
                    b.Navigation("Appeals");

                    b.Navigation("AssignedTasks");

                    b.Navigation("AssignedZones");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("ReportedIssues");

                    b.Navigation("SupervisedWorkers");
                });

            modelBuilder.Entity("FollowUp.Core.Entities.Zone", b =>
                {
                    b.Navigation("AssignedUsers");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("Issues");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
