// <auto-generated />
using System;
using Jawlah.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Jawlah.Infrastructure.Data.Migrations
{
    [DbContext(typeof(JawlahDbContext))]
    [Migration("20260112012631_SyncSchemaCleanup")]
    partial class SyncSchemaCleanup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jawlah.Core.Entities.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("CheckInEventTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("CheckInLatitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double>("CheckInLongitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<DateTime?>("CheckInSyncTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutEventTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CheckOutLatitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double?>("CheckOutLongitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<DateTime?>("CheckOutSyncTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ValidationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan?>("WorkDuration")
                        .HasColumnType("time");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Attendance_Status");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("IX_Attendance_ZoneId");

                    b.HasIndex("UserId", "CheckInEventTime")
                        .HasDatabaseName("IX_Attendance_User_CheckIn");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.Issue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IssueId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Longitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SyncTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("IssueId");

                    b.HasIndex("ReportedAt");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("Severity");

                    b.HasIndex("Type");

                    b.HasIndex("ZoneId");

                    b.HasIndex("ReportedByUserId", "Status")
                        .HasDatabaseName("IX_Issue_Reporter_Status");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.LocationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Accuracy")
                        .HasColumnType("float");

                    b.Property<double?>("Heading")
                        .HasColumnType("float");

                    b.Property<bool>("IsSync")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double>("Longitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double?>("Speed")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp")
                        .HasDatabaseName("IX_LocationHistory_User_Timestamp");

                    b.ToTable("LocationHistories");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FcmMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PayloadJson")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsSent");

                    b.HasIndex("Type");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("IX_Notification_User_IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("IssueId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("PhotoId");

                    b.HasIndex("IssueId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("IX_Photos_UploadedAt");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_Photos_EntityType_EntityId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("Longitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresPhotoProof")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SyncTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int");

                    b.Property<int?>("TaskType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("DueDate");

                    b.HasIndex("Priority");

                    b.HasIndex("ZoneId");

                    b.HasIndex("AssignedToUserId", "Status")
                        .HasDatabaseName("IX_Task_AssignedUser_Status");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pin")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("WorkerType")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email");

                    b.HasIndex("Pin")
                        .IsUnique()
                        .HasFilter("[Pin] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.UserZone", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "ZoneId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_UserZone_IsActive");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserZone_UserId");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("IX_UserZone_ZoneId");

                    b.ToTable("UserZones");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.Zone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"));

                    b.Property<double>("AreaSquareMeters")
                        .HasColumnType("float");

                    b.Property<Geometry>("Boundary")
                        .HasColumnType("geography");

                    b.Property<string>("BoundaryGeoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CenterLatitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<double>("CenterLongitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("float(18)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<DateTime>("VersionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ZoneCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ZoneId");

                    b.HasIndex("District");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Zone_IsActive");

                    b.HasIndex("ZoneCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Zone_ZoneCode_Unique");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.Attendance", b =>
                {
                    b.HasOne("Jawlah.Core.Entities.User", "User")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jawlah.Core.Entities.Zone", "Zone")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.Issue", b =>
                {
                    b.HasOne("Jawlah.Core.Entities.User", "ReportedByUser")
                        .WithMany("ReportedIssues")
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jawlah.Core.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jawlah.Core.Entities.Zone", "Zone")
                        .WithMany("Issues")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReportedByUser");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.LocationHistory", b =>
                {
                    b.HasOne("Jawlah.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.Notification", b =>
                {
                    b.HasOne("Jawlah.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.Photo", b =>
                {
                    b.HasOne("Jawlah.Core.Entities.Issue", null)
                        .WithMany("Photos")
                        .HasForeignKey("IssueId");

                    b.HasOne("Jawlah.Core.Entities.Task", null)
                        .WithMany("Photos")
                        .HasForeignKey("TaskId");

                    b.HasOne("Jawlah.Core.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("Jawlah.Core.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.Task", b =>
                {
                    b.HasOne("Jawlah.Core.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jawlah.Core.Entities.User", "AssignedToUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jawlah.Core.Entities.Zone", "Zone")
                        .WithMany("Tasks")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.UserZone", b =>
                {
                    b.HasOne("Jawlah.Core.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jawlah.Core.Entities.User", "User")
                        .WithMany("AssignedZones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jawlah.Core.Entities.Zone", "Zone")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.Issue", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.Task", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("AssignedZones");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReportedIssues");
                });

            modelBuilder.Entity("Jawlah.Core.Entities.Zone", b =>
                {
                    b.Navigation("AssignedUsers");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("Issues");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
